### ISSUE TITLE
Bullets Below Embed Lose Indentation

### ISSUE THREAD

**Issue by mgworldwide** [GnoxNahte/obsidian-auto-embed#10]
When you include bullet points directly below an indented embed, they lose their indentation.

How to Replicate:
- Create a bullet list.
- Embed media into an indented bullet.
- Create a bullet list below it.
- Delete the gap between the media and the bullet below.

**Comment by GnoxNahte** [comment]
Hey as I mentioned in another issue, I might take a while to solve this bug (assuming I can solve it)

For now, here's 2 workarounds:
- Try viewing it in Reading mode if you don't need to edit it
- Add a space after the closing bracket of the markdown. Example: `![](url)<space>`

**Comment by mgworldwide** [comment]
No problem, thanks for the alternatives. 

Also nice to see how active you are on here, lots of plugins I know of haven't been updated in a while so that's kinda sad.
