### ISSUE TITLE
Can't Unindent an Indented Bullet Below Embed

### ISSUE THREAD

**Issue by mgworldwide** [GnoxNahte/obsidian-auto-embed#11]
When a bullet list is below an indented embed, you can't unindent it. It just goes back to the embed link rather than going fully back. 

How to Replicate:
- Create a bullet list.
- Embed media in an indented bullet.
- Create another bullet below it.
- Try to unindent the bullet below the media (by pressing backspace before the text.

The only fix to this is pressing enter so that the originally indented bullet is now unindented.

**Comment by GnoxNahte** [comment]
Hey as I mentioned in another issue, I might take a while to solve this bug (assuming I can solve it)

For now, here's a workaround:
- If you are having trouble editing it, try editing it in Source Mode
