### ISSUE TITLE
Unwanted "Link" Hyperlink Appears Under Embed

### ISSUE THREAD

**Issue by mgworldwide** [GnoxNahte/obsidian-auto-embed#14]
A hyperlink to the media named "Link" appears under a piece of media (namely when embedding a twitter account (regardless whether it's in a bullet list, indented or just embedded as is).

How to replicate:
1. Copy the URL of an X/Twitter account.
2. Paste it into a file.

I'm not sure this happens to other media (from what I know of, tweets work fine and so do YouTube videos). 

Twitter accounts also load with many popups (although I'm not sure if this is changeable) (mentioned in #13)

**Comment by GnoxNahte** [comment]
This happens when the plugin doesn't support the embed. So by default, it'll embed the whole page without any modifications and add a "Link" hyperlink.

**Comment by GnoxNahte** [comment]
I'll close it for now as Twitter profiles aren't supported. Feel free to reopen it if I misunderstood it or there's another issue.

Note that this plugin doesn't embed YouTube & Twitter links as [Obsidian already embeds ](https://help.obsidian.md/Editing+and+formatting/Embed+web+pages) them. For Twitter, Obsidian supports `twitter.com` but not `x.com` so this plugin just embeds `x.com`. However, after Obsidian 1.7.0, [Obsidian will support x.com](https://obsidian.md/changelog/2024-08-08-desktop-v1.7.0/) by default. So this plugin won't embed any Twitter links (from both `twitter.com` & `x.com`) after Obsidian 1.7.0.

If you are curious why I don't override Obsidian's embeds for YouTube & Twitter: https://github.com/GnoxNahte/obsidian-auto-embed/issues/7#issuecomment-2308823643

**Comment by mgworldwide** [comment]
Okay thanks, that worked, should've checked the settings fully first!

However, another instance of this happening was for Google Cover images (that I'd retrieve from the "Book Search" plugin). This affected my databases.

Once I turned it off, I'm faced with another issue (it doesn't load and instead shows this):

`
<html>
<body>

Loading embed...Link: http://books.google.com/books/content?id=iEwHAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api
--


<br class="Apple-interchange-newline">
</body>
</html>
`

When I turn off auto embed, this stops happening. 

Perhaps there could be a filter to stop auto embed from trying to embed google covers or perhaps an integration of it at some point?

**Comment by GnoxNahte** [comment]
I made it so that it detects if it's a web image before embedding. However, it might have a split second showing the placeholder which might not be good. I'm also not sure if the CSS to hide the image works with the Book Search plugin too. 

I might add a filter in the future too. 

Meanwhile, if it still doesn't work, is it possible to add a `noembed` option as shown [here](https://github.com/GnoxNahte/obsidian-auto-embed#:~:text=noembed,https%3A//example.com)?
