### ISSUE TITLE
FR: Improve Embedding of Twitter Accounts

### ISSUE THREAD

**Issue by mgworldwide** [GnoxNahte/obsidian-auto-embed#15]
I've put this as a feature request because it's not really a bug, just a QOL thing. When you embed a Twitter account, it shows many popups (cookies and signup/login).

Ideally, you'd just be able to access the website without any of that popping up. 

However, I know how weird Twitter can be with its embedding, API and such so this could just be impossible (for now at least).

**Comment by GnoxNahte** [comment]
Well, this is the best I can do. Embeds the timeline (latest posts). Not the profile though. Should I add it?
![image](https://github.com/user-attachments/assets/50e60d35-0283-454b-8fe7-a319c0f93724)

**Comment by mgworldwide** [comment]
Sure, why not? I think it would be useful for viewing someone's top posts. 

Maybe add a section in the list of supported websites in the settings to tell people it's only the top posts.

**Comment by GnoxNahte** [comment]
Added! Note that it doesn't work with non-verified accounts for some reason.
