### ISSUE TITLE
embed Instagram post

### ISSUE THREAD

**Issue by bleedingsaber** [GnoxNahte/obsidian-auto-embed#17]
Not sure is this possible or not, just feel Instagram has more limit than TikTok.

**Comment by GnoxNahte** [comment]
I've added it, but let me make some other improvements to the plugin first. I should be able to make a new release by the end of today!

Note that I don't use Instagram so I have no idea how well it'll work. Tried it with some links so it should work with most of them for now. If something doesn't work, just comment in this issue or create a new issue. Thanks!

**Comment by bleedingsaber** [comment]
Really thanks for your quick reply, if having anything, I will post here. You are amazing!
