### ISSUE TITLE
Bug report singleword with colon (non-hyperlink) detected as hyperlink

### ISSUE THREAD

**Issue by ksdavidc** [GnoxNahte/obsidian-auto-embed#19]
### What happened?

https://github.com/user-attachments/assets/84841714-fc3c-4e04-aac0-ee2eb4b61111

### Sample Markdown

see above

### Errors

<img width="450" alt="Screenshot 2024-10-28 at 5 26 15 AM" src="https://github.com/user-attachments/assets/64d1682c-726f-465f-b629-0fc87275470b">

### Obsidian Version

Version 1.7.4 (Installer 1.6.5)

### Plugin Version

latest

### OS

MacOS

**Comment by GnoxNahte** [comment]
Hi, thanks for reporting the bug! 

I've uploaded a new release with the fix!
