### ISSUE TITLE
Command palette usage

### ISSUE THREAD

**Issue by mar-drik** [GnoxNahte/obsidian-auto-embed#2]
Hi there,

please, let me inform you that Auto Embed inserts incorrect mardown syntax when used via Command palette (Ctrl+P). The syntax it inserts is `![[]]` instead of the expected one `![]()`

This is especially annoying for a mobile app. Thank you for the understanding.
Though, love your plugin!

**Comment by GnoxNahte** [comment]
Hi, I'm assuming you mean the "Add Embed" command? If so, the command is from Obsidian. I haven't created a command for creating an embed through the command palette yet. 

Good suggestion though, I'll try to do it and put it in the next release. 

Thanks for the feedback and liking the plugin! If you got any other feedback feel free to create new issues.

**Comment by GnoxNahte** [comment]
Actually after thinking for a while I think I'll add a "Convert to embed" command but I won't add a "Add embed link" command. 

To add an embed, you can already paste a link and the plugin will suggest to create an embed using that link. I think it's easier than going through the command palette and having a prompt to enter the url. Most of the times, users are going to paste links anyway. 

If you think I should change comment below? Thanks in advance.

**Comment by mar-drik** [comment]
Yes I did assume "Add Embed" command and sry, didn't know it's built in, not yours.

Anyway, regarding to your suggestion about the command. The funcionality you've implemented with context menu is really great and I appreciate it in desktop version. However my main usage is on mobile device and it is a problem there. Even typing  correct markdown notation is quite unfriendly on mobile keyboard, so adding a URL via command palette gives me a lot of sense. 

Thank you, you are paying attention to this.

**Comment by GnoxNahte** [comment]
It's ok! I would've probably made the same mistake without knowing too.

I can try adding an "Auto Embed: Add Embed" command. I'll do it similar to the "Add Embed" command from Obsidian where I'll put in the markdown and have the cursor inside the place to put the link if it's ok?

**Comment by GnoxNahte** [comment]
I updated the plugin and added the "Auto Embed: Add embed" and "Auto Embed: Mark to embed" commands. I hope this solves it! Please test it and if there are any issues you can reopen this discussion.

Release: https://github.com/GnoxNahte/obsidian-auto-embed/tree/1.0.4
