### ISSUE TITLE
[FEATURE]: Embed SoundCloud songs

### ISSUE THREAD

**Issue by Rikiub** [GnoxNahte/obsidian-auto-embed#3]
You can see a example in [Iframely](https://iframely.com/domains/soundcloud)

![image](https://github.com/user-attachments/assets/38350844-cbb6-4321-8426-c9a7172b1752)

**Comment by GnoxNahte** [comment]
Hey I was looking through SoundCloud's docs and found [these options](https://developers.soundcloud.com/docs/api/html5-widget). Was thinking of putting "**Auto Play**" and "**Single Active**" in the options. Keeping it to 2 options to keep it simple. Do you think its good? Do you want any other options?

**Comment by GnoxNahte** [comment]
Actually after thinking about it, I think I won't add **Auto play** and **Single Active** as options. I don't see why Auto Play should be enabled. It feels like it'll be quite messy as every time you open the note, it'll play the song. Unless you want to have specific notes play their own songs when you open it?

Just comment here if you feel like you want the setting to be there. I'll just disable Auto Play from the start and won't set any value to Single Active.

**Comment by GnoxNahte** [comment]
Hey, I added it into the latest version - [1.1.1](https://github.com/GnoxNahte/obsidian-auto-embed/tree/1.1.1). If you face any problems with it or have any feedback, you can reopen the issue.

**Comment by Rikiub** [comment]
> Actually after thinking about it, I think I won't add **Auto play** and **Single Active** as options. I don't see why Auto Play should be enabled. It feels like it'll be quite messy as every time you open the note, it'll play the song. Unless you want to have specific notes play their own songs when you open it?
> 
> Just comment here if you feel like you want the setting to be there. I'll just disable Auto Play from the start and won't set any value to Single Active.

In my opinion, I prefer don't have **auto play** enabled because I wouldn't like heard music each time that I open a note (xD).

But wow, you implement this so fast! Thanks so much!

**Comment by GnoxNahte** [comment]
Great! Autoplay is disabled for now.

Haha ya. It's the weekend and I'm free :)
