### ISSUE TITLE
[FEATURE]: Embed TikTok videos

### ISSUE THREAD

**Issue by Rikiub** [GnoxNahte/obsidian-auto-embed#4]
You can see a example in [Iframely](https://iframely.com/domains/tiktok).

**Comment by GnoxNahte** [comment]
Hey, I added it into the latest version - [1.1.1](https://github.com/GnoxNahte/obsidian-auto-embed/tree/1.1.1). If you face any problems with it or have any feedback, you can reopen the issue.

**Comment by Rikiub** [comment]
Ok, I found a bug.

In **Reading View** the video looks great:

![image](https://github.com/user-attachments/assets/d0814dd4-3630-4593-a53d-8db58be73669)

But when I switch to **Live Preview** the video is cropped:

![image](https://github.com/user-attachments/assets/bcb94385-a34c-46bb-8218-ec2bd8057a0c)

**Comment by GnoxNahte** [comment]
Thanks for the report! It also gave me the idea of caching the sizes so embeds that are resizeable should be resized faster after the first time it loads. I'll make a new update after confirming the bug in [Issue 5](https://www.github.com/GnoxNahte/obsidian-auto-embed/issues/5)
