### ISSUE TITLE
Uncollapsable  Embed

### ISSUE THREAD

**Issue by mgworldwide** [GnoxNahte/obsidian-auto-embed#9]
If you include the embed in a bulleted list and collapse it, it still shows up.

How to Replicate:
- Create a bulleted list with at least one indentation.
- Embed a piece of media (e.g. tweet) in an indented bullet point.
- Collapse the bullet point above it.

**Comment by Overdrive8911** [comment]
Sorry, if this is the wrong place but I wanted to add that this also doesn't work with headings too.

**Comment by GnoxNahte** [comment]
It's ok! Here's fine.

Just tested and it works for me though
```markdown
## Heading 2
![](https://obsidian.md/)
```
